import os

AWS_SERVER_PUBLIC_KEY = os.environ.get('ANGELA_AWS_SERVER_PUBLIC_KEY')
AWS_SERVER_SECRET_KEY = os.environ.get('ANGELA_AWS_SERVER_SECRET_KEY')
AWS_REGION = 'us-east-1'

AWS_SES_SMTP_USERNAME = os.environ.get('ANGELA_AWS_SMTP_USERNAME')
AWS_SES_SMTP_PASSWORD = os.environ.get('ANGELA_AWS_SMTP_PASSWORD')

RECIPIENT_EMAIL = os.environ.get('ANGELA_PERSONAL_EMAIL')
